version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    networks:
      - coffee-mysql
    environment:
    - MYSQL_ROOT_USER=1
    - MYSQL_PASSWORD=Dolphin28
    - MYSQL_ROOT_PASSWORD=Dolphin28
    - MYSQL_DATABASE=coffee_base
    ports:
      - "3307:3307"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3307" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  coffee-maker-app:
    build:
      context: .
    container_name: coffee-app
    image: coffee-maker-app
    ports:
      - "8081:8080"
    networks:
      - coffee-mysql
    depends_on:
      - mysqldb
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/coffee_base?useSSL=false&connectionTimeZone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true
    restart: on-failure
networks:
  coffee-mysql:
