version: '3'
services:

  mysqldb:
    container_name: mysqldb
    image: mysql:8
    networks:
      - coffee-mysql
    environment:
      - MYSQL_USER=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=coffee_base
      - MYSQL_ROOT_PASSWORD=1234

    ports:
      - "3307:3307"
    restart: always

  coffee-maker-app:
    build:
      context: .
    container_name: coffee-spring
    image: coffee-maker-app
    ports:
      - "8081:8080"
    networks:
      - coffee-mysql
    depends_on:
      - mysqldb
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/coffee_base?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true

networks:
  coffee-mysql:
